### PR TITLE
Refactor: Code for fetching pluralization

### PR DESCRIPTION
**Pull request by manojmj92**
Firstly, thanks for creating the gem. I really like how simple the `pluralization` implementation is.

I was just reading through the code and found an area for improvement.
It is just a straight forward refactor.

Thank you.

### CODE REVIEW

**Comment by markets** [comment]
Hi @manojmj92 👋 and thanks a lot! I'm trying to keep code for this gem as simple and straightforward as possible. Btw, your changes are wrong, if you pass, for example `count: 5`, it will return `nil` instead of the `many` keyword. I also prefer in general the `hash + fetch` construct, but it doesn't fit/work well in this case. 

That said, I realized I need to add more tests to catch those cases, because right now we are just checking 0, 1 and 2 values:

https://github.com/markets/mini_i18n/blob/74f0d6ebaadf09eed3bfe5f5075faf06eb7abde1/spec/mini_i18n_spec.rb#L89-L93

So, CI is green, but it should fail with these changes.

Thanks!

**Comment by manojmj92** [comment]
Hey Marc,

Thanks for the response. Great catch on the edge case. Can we solve it
using Hash#default?

**Comment by markets** [comment]
Yes, using `Hash#default` or even different things like a shortcut `IF` as first statement, but not sure if final code will be simpler to read and maintain:

- current: switch/case

`vs`

- new: constant + hash + fetch + default

**Comment by manojmj92** [comment]
Got it. That makes sense. Thanks Marc! :)

**Pull request closed without merging**
